---

- name: install docker-compose
  pip: name=docker-compose version={{ compose_vers }}

- name: copy docker-compose file for postgres
  copy: src=../files/docker-compose.yml dest={{ home_folder }}

- name: run docker image
  docker_service:
    project_src: "{{ home_folder }}"